# Generated by Django 5.0 on 2024-01-17 08:27

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Comments",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(blank=True, upload_to="comments/")),
                ("body", models.TextField(blank=True, null=True)),
                ("name", models.CharField(max_length=200)),
                ("email", models.EmailField(max_length=256)),
                ("approve_comment", models.BooleanField(default=False)),
            ],
            options={
                "verbose_name": "Comment",
                "verbose_name_plural": "Comments",
            },
        ),
        migrations.CreateModel(
            name="Transactions",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("bitcoin_address", models.CharField(max_length=100)),
                (
                    "bitcoin_amount",
                    models.DecimalField(decimal_places=6, max_digits=7, max_length=100),
                ),
                ("browser_id", models.CharField(max_length=34)),
                (
                    "payment_status",
                    models.BooleanField(blank=True, default=False, null=True),
                ),
                (
                    "transaction_type",
                    models.CharField(
                        choices=[("deposit", "Deposit"), ("withdrawal", "Withdrawal")],
                        default="deposit",
                        max_length=30,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Transaction",
                "verbose_name_plural": "Transactions",
            },
        ),
        migrations.CreateModel(
            name="Wallet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("address", models.CharField(blank=True, max_length=200)),
                ("chain_name", models.CharField(blank=True, max_length=200)),
                ("nonce", models.CharField(blank=True, max_length=200)),
                (
                    "balance",
                    models.DecimalField(blank=True, decimal_places=4, max_digits=6),
                ),
                ("browser_id", models.CharField(blank=True, max_length=200)),
            ],
        ),
    ]
