# Generated by Django 5.0 on 2024-01-01 08:12

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Comments",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Transactions",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("bitcoin_address", models.CharField(max_length=100)),
                (
                    "bitcoin_amount",
                    models.DecimalField(decimal_places=6, max_digits=7, max_length=100),
                ),
                ("browser_id", models.CharField(max_length=34)),
                (
                    "payment_status",
                    models.BooleanField(blank=True, default=False, null=True),
                ),
            ],
            options={
                "verbose_name": "Transaction",
                "verbose_name_plural": "Transactions",
            },
        ),
    ]
