# Generated by Django 5.0 on 2024-01-01 08:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0002_transactions_created_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="transactions",
            name="transaction_type",
            field=models.CharField(
                choices=[("deposit", "Deposit"), ("withdrawal", "Withdrawal")],
                default="deposit",
                max_length=30,
            ),
        ),
    ]
