# Generated by Django 5.0 on 2024-01-09 10:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0003_transactions_transaction_type"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="comments",
            options={"verbose_name": "Comment", "verbose_name_plural": "Comments"},
        ),
        migrations.AddField(
            model_name="comments",
            name="body",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="comments",
            name="email",
            field=models.EmailField(default="", max_length=256),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="comments",
            name="image",
            field=models.ImageField(blank=True, upload_to="comments/"),
        ),
        migrations.AddField(
            model_name="comments",
            name="name",
            field=models.CharField(default="", max_length=200),
            preserve_default=False,
        ),
    ]
