# Generated by Django 5.0 on 2024-01-09 10:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0004_alter_comments_options_comments_body_comments_email_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="comments",
            name="approve_comment",
            field=models.BooleanField(default=False),
        ),
    ]
