# Generated by Django 5.0 on 2024-01-14 20:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0005_comments_approve_comment"),
    ]

    operations = [
        migrations.CreateModel(
            name="Wallet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("address", models.CharField(blank=True, max_length=200)),
                ("chain_name", models.CharField(blank=True, max_length=200)),
                ("nonce", models.CharField(blank=True, max_length=200)),
                (
                    "balance",
                    models.DecimalField(blank=True, decimal_places=4, max_digits=6),
                ),
            ],
        ),
    ]
