# Generated by Django 5.0 on 2024-01-14 20:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0006_wallet"),
    ]

    operations = [
        migrations.AddField(
            model_name="wallet",
            name="browser_id",
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
